apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jmeter-vts
  labels:
    app: {{ .Release.Name }}-jmeter-vts
spec:
  type: {{ .Values.jmeterVts.service.type | default "ClusterIP" }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-jmeter-vts
