apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-telegraf
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-telegraf
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-telegraf
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-telegraf
        dynatrace.com/injection: "disabled"
      annotations:
        dynatrace.com/injected: "false"
    spec:
      serviceAccountName: {{ .Release.Name }}-telegraf
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 65534
      containers:
        - name: telegraf
          image: telegraf:1.25
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
            - name: cri-socket
              mountPath: /var/run/crio/crio.sock
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-telegraf-config
            items:
              - key: telegraf.conf
                path: telegraf.conf
        - name: cri-socket
          hostPath:
            path: /var/run/crio/crio.sock
            type: Socket
      tolerations:
        - operator: "Exists"
      restartPolicy: Always
