# ServiceAccount for Telegraf
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-telegraf
  namespace: {{ .Release.Namespace }}

---
# ClusterRole with permissions needed by Telegraf to collect metrics and Kubernetes info
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-telegraf
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/stats
      - nodes/stats/summary
      - pods
      - services
      - endpoints
      - persistentvolumes
      - persistentvolumeclaims
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch

---
# Bind the ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-telegraf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-telegraf
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-telegraf
    namespace: {{ .Release.Namespace }}
